# Properties of Dot Product - Lab

## Introduction

In this lab, you'll be practicing some interesting properties of a dot product-type matrix multiplication. Understanding these properties will become useful as you study machine learning. The lab will require you to calculate results to provide a proof for these properties.

## Objectives

In this lab you will: 

- Demonstrate the distributive, commutative, and associative property of dot products 
- Use the transpose method to transpose Numpy matrices 
- Compute the dot product for matrices and vectors 


## Instructions

* For each property, create suitably sized matrices with random data to prove the equations 
* Ensure that size/dimension assumptions are met while performing calculations (you'll see errors otherwise)
* Calculate the LHS and RHS for all equations and show if they are equal or not

## Distributive Property - matrix multiplication IS distributive

### Prove that $A \cdot (B+C) = (A \cdot B + A \cdot C) $

In [1]:
import numpy as np

In [4]:
# Making the matrices:
A = np.random.randint(10, size=(3, 2))
B = np.random.randint(10, size=(2, 2))
C = np.random.randint(10, size=(2, 1))

# Left hand side:
lhs = A.dot(B + C)

# Right hand side:
rhs = A.dot(B) + A.dot(C)

print("Left Hand Side:\n", lhs)
print("Right Hand Side:\n", rhs)
print(lhs == rhs)

Left Hand Side:
 [[160 104]
 [184 128]
 [ 67  32]]
Right Hand Side:
 [[160 104]
 [184 128]
 [ 67  32]]
[[ True  True]
 [ True  True]
 [ True  True]]


## Associative Property - matrix multiplication IS associative
### Prove that $A \cdot (B \cdot C) = (A \cdot B) \cdot C $

In [5]:
lhs = A.dot(B.dot(C))
rhs = (A.dot(B)).dot(C)

print("Left Hand Side:\n", lhs)
print("Right Hand Side:\n", rhs)
print(lhs == rhs)

Left Hand Side:
 [[602]
 [728]
 [203]]
Right Hand Side:
 [[602]
 [728]
 [203]]
[[ True]
 [ True]
 [ True]]


## Commutative Property - matrix multiplication is NOT commutative
### Prove that for matrices, $A \cdot B \neq B \cdot A $

In [6]:
lhs = A.dot(B)
rhs = B.dot(A)

print("Left Hand Side:\n", lhs)
print("Right Hand Side:\n", rhs)
print(lhs == rhs)

ValueError: shapes (2,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

## Commutative Property -  vector multiplication IS commutative
### Prove that for vectors,  $x^T \cdot y = y^T \cdot x$
Note: superscipt<sup>T</sup> denotes the transpose we saw earlier

In [9]:
x = np.random.randint(10, size=(3,))
y = np.random.randint(10, size=(3,))

lhs = x.T.dot(y)
rhs = y.T.dot(x)
print("Left Hand Side:\n", lhs)
print("Right Hand Side:\n", rhs)
print(lhs == rhs)

Left Hand Side:
 59
Right Hand Side:
 59
True


In [13]:
print(x.T * y)
print(y.T * x)

[48  9  2]
[48  9  2]


## Simplification of the matrix product
### Prove that $ (A \cdot B)^T = B^T \cdot A^T $

In [14]:
lhs = (A.dot(B)).T
rhs = B.T.dot(A.T)

print("Left Hand Side:\n", lhs)
print("Right Hand Side:\n", rhs)
print(lhs == rhs)

Left Hand Side:
 [[110 128  44]
 [ 54  72   9]]
Right Hand Side:
 [[110 128  44]
 [ 54  72   9]]
[[ True  True  True]
 [ True  True  True]]


## Summary 

You've seen enough matrix algebra by now to solve a problem of linear equations as you saw earlier. You'll now see how to do this next. 